version: 2.1

jobs:
  build-gatsby:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build Gatsby site
          command: npm run build

      - persist_to_workspace:
          root: public
          paths:
            - .

  deploy:
    docker:
      - image: node:20
    steps:
      - attach_workspace:
          at: ~/artifacts
      - run:
          name: Install wrangler
          command: npm install -g wrangler
      - run:
          name: Deploy to Cloudflare Pages
          command: |
            wrangler pages deploy ~/artifacts \
              --project-name=my-new-static-site \
              --commit-dirty=true


workflows:
  build-and-deploy:
    jobs:
      - build-gatsby
      - deploy:
          requires:
            - build-gatsby
